apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: poc-archi-kube
  name: poc-archi-kube
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/poc-archi-kube
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: poc-archi-kube
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: poc-archi-kube
    spec:
      containers:
      - image: us.icr.io/poc-archi-logi-registry/hello-containers-20190910230748396:latest
        imagePullPolicy: IfNotPresent
        name: poc-archi-kube
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
