spring:
  application:
    name: '@project.name@'
  profiles:
    active: '@spring.profiles.active@'
  jpa:
    mapping-resources: 
      - META-INF/common.orm.hbm.xml
      - META-INF/customer.orm.hbm.xml
      - META-INF/account.orm.hbm.xml
    open-in-view: false
    database: h2
  cache:
    jcache:
      config: classpath:cache/ehcache.xml
# Logging Configurations
application: 
  orgEntity: MyCompany
  version: '@project.version@'
  timezone: ${user.timezone}
  apCode: AP2020
  type: service_logs
  log-file-name: ${spring.application.name}-${application.apCode}
logging:
  level:
    ROOT: INFO
    org.springframework: INFO
